### ISSUE TITLE
What is the reason for `swiss-army-knife` binary (and the server.go)?

### ISSUE THREAD

**Issue by shalak** [leodotcloud/swiss-army-knife#29]
What is the purpose of the `/usr/bin/swiss-army-knife` binary? Is it only a dummy service, that is kept running, so the container doesn't stop automatically?

The README.md mentions:

> This image also includes a very small web application for testing/debugging purposes.

What features does it provide, other than hosting the homepage with NATO alphabet?

**Comment by leodotcloud** [comment]
Yes, it's a simple web server. It can listen on any port specified via PORT environment variable. What's shown on the homepage can be controlled via "ALPHABET" variable. With the same code, we can simulate multiple applications that can be used for testing k8s services, ingress, port mappings, etc. I hope this helps.
